### PR TITLE
DPM-53: Added support for authenticated access to a remote Blob Store.

### PR DESCRIPTION
**Pull request by sjacob**
@ninhnguyen @brycollins @ato @jrixon @terenceingram 
This change adds support for authenticated access to a remote Blob Store. It finishes implementing the design outlined in https://github.com/nla/doss/blob/master/doc/authentication.md except that support for remote administration functions (ie: staging) isn't supported. Admin functions through the CLI still require direct access to the local blob store.

Currently only SSL authentication is supported. I will look at adding OpenID Connect over SASL support if the wildfly-elytron library provides a suitable SASL implementation.

I have also changed all logging to use SLF4J.

### CODE REVIEW

**Comment by nlabuilder** [comment]
SonarQube analysis reported 956 issues
* CRITICAL 65 critical
* MAJOR 338 major
* MINOR 553 minor

#### Top 10 issues

1. CRITICAL [BlobStoreServer.java#L168](https://github.com/nla/doss/blob/7a8e690c73c53c0eb4b475662907f6a431b4e19b/src/doss/net/BlobStoreServer.java#L168): Use a logger to log this exception. [rule](https://sonarqube.nla.gov.au/coding_rules#rule_key=squid%3AS1148)
1. CRITICAL [ClientResponse.java#L38](https://github.com/nla/doss/blob/7a8e690c73c53c0eb4b475662907f6a431b4e19b/src/doss/net/ClientResponse.java#L38): Add a "clone()" method to this class. [rule](https://sonarqube.nla.gov.au/coding_rules#rule_key=squid%3AS2157)
1. CRITICAL [ClientResponse.java#L498](https://github.com/nla/doss/blob/7a8e690c73c53c0eb4b475662907f6a431b4e19b/src/doss/net/ClientResponse.java#L498): Change this condition so that it does not always evaluate to "true" [rule](https://sonarqube.nla.gov.au/coding_rules#rule_key=squid%3AS2583)
1. CRITICAL [ClientResponse.java#L499](https://github.com/nla/doss/blob/7a8e690c73c53c0eb4b475662907f6a431b4e19b/src/doss/net/ClientResponse.java#L499): Change this condition so that it does not always evaluate to "false" [rule](https://sonarqube.nla.gov.au/coding_rules#rule_key=squid%3AS2583)
1. CRITICAL [ClientResponse.java#L499](https://github.com/nla/doss/blob/7a8e690c73c53c0eb4b475662907f6a431b4e19b/src/doss/net/ClientResponse.java#L499): Change this condition so that it does not always evaluate to "true" [rule](https://sonarqube.nla.gov.au/coding_rules#rule_key=squid%3AS2583)
1. CRITICAL [ClientResponse.java#L505](https://github.com/nla/doss/blob/7a8e690c73c53c0eb4b475662907f6a431b4e19b/src/doss/net/ClientResponse.java#L505): Change this condition so that it does not always evaluate to "true" [rule](https://sonarqube.nla.gov.au/coding_rules#rule_key=squid%3AS2583)
1. CRITICAL [ClientResponse.java#L506](https://github.com/nla/doss/blob/7a8e690c73c53c0eb4b475662907f6a431b4e19b/src/doss/net/ClientResponse.java#L506): Change this condition so that it does not always evaluate to "true" [rule](https://sonarqube.nla.gov.au/coding_rules#rule_key=squid%3AS2583)
1. CRITICAL [ClientResponse.java#L514](https://github.com/nla/doss/blob/7a8e690c73c53c0eb4b475662907f6a431b4e19b/src/doss/net/ClientResponse.java#L514): Change this condition so that it does not always evaluate to "true" [rule](https://sonarqube.nla.gov.au/coding_rules#rule_key=squid%3AS2583)
1. CRITICAL [ClientResponse.java#L515](https://github.com/nla/doss/blob/7a8e690c73c53c0eb4b475662907f6a431b4e19b/src/doss/net/ClientResponse.java#L515): Change this condition so that it does not always evaluate to "true" [rule](https://sonarqube.nla.gov.au/coding_rules#rule_key=squid%3AS2583)
1. CRITICAL [ClientResponse.java#L523](https://github.com/nla/doss/blob/7a8e690c73c53c0eb4b475662907f6a431b4e19b/src/doss/net/ClientResponse.java#L523): Change this condition so that it does not always evaluate to "true" [rule](https://sonarqube.nla.gov.au/coding_rules#rule_key=squid%3AS2583)

**Comment by nlabuilder** [comment]
Build finished.

**Comment by nlabuilder** [comment]
SonarQube analysis reported 954 issues
* CRITICAL 64 critical
* MAJOR 337 major
* MINOR 553 minor

#### Top 10 issues

1. CRITICAL [ClientResponse.java#L38](https://github.com/nla/doss/blob/568c6995e151e468362c2544b7856a67120042c1/src/doss/net/ClientResponse.java#L38): Add a "clone()" method to this class. [rule](https://sonarqube.nla.gov.au/coding_rules#rule_key=squid%3AS2157)
1. CRITICAL [ClientResponse.java#L498](https://github.com/nla/doss/blob/568c6995e151e468362c2544b7856a67120042c1/src/doss/net/ClientResponse.java#L498): Change this condition so that it does not always evaluate to "true" [rule](https://sonarqube.nla.gov.au/coding_rules#rule_key=squid%3AS2583)
1. CRITICAL [ClientResponse.java#L499](https://github.com/nla/doss/blob/568c6995e151e468362c2544b7856a67120042c1/src/doss/net/ClientResponse.java#L499): Change this condition so that it does not always evaluate to "true" [rule](https://sonarqube.nla.gov.au/coding_rules#rule_key=squid%3AS2583)
1. CRITICAL [ClientResponse.java#L499](https://github.com/nla/doss/blob/568c6995e151e468362c2544b7856a67120042c1/src/doss/net/ClientResponse.java#L499): Change this condition so that it does not always evaluate to "false" [rule](https://sonarqube.nla.gov.au/coding_rules#rule_key=squid%3AS2583)
1. CRITICAL [ClientResponse.java#L505](https://github.com/nla/doss/blob/568c6995e151e468362c2544b7856a67120042c1/src/doss/net/ClientResponse.java#L505): Change this condition so that it does not always evaluate to "true" [rule](https://sonarqube.nla.gov.au/coding_rules#rule_key=squid%3AS2583)
1. CRITICAL [ClientResponse.java#L506](https://github.com/nla/doss/blob/568c6995e151e468362c2544b7856a67120042c1/src/doss/net/ClientResponse.java#L506): Change this condition so that it does not always evaluate to "true" [rule](https://sonarqube.nla.gov.au/coding_rules#rule_key=squid%3AS2583)
1. CRITICAL [ClientResponse.java#L514](https://github.com/nla/doss/blob/568c6995e151e468362c2544b7856a67120042c1/src/doss/net/ClientResponse.java#L514): Change this condition so that it does not always evaluate to "true" [rule](https://sonarqube.nla.gov.au/coding_rules#rule_key=squid%3AS2583)
1. CRITICAL [ClientResponse.java#L515](https://github.com/nla/doss/blob/568c6995e151e468362c2544b7856a67120042c1/src/doss/net/ClientResponse.java#L515): Change this condition so that it does not always evaluate to "true" [rule](https://sonarqube.nla.gov.au/coding_rules#rule_key=squid%3AS2583)
1. CRITICAL [ClientResponse.java#L523](https://github.com/nla/doss/blob/568c6995e151e468362c2544b7856a67120042c1/src/doss/net/ClientResponse.java#L523): Change this condition so that it does not always evaluate to "true" [rule](https://sonarqube.nla.gov.au/coding_rules#rule_key=squid%3AS2583)
1. CRITICAL [ClientResponse.java#L524](https://github.com/nla/doss/blob/568c6995e151e468362c2544b7856a67120042c1/src/doss/net/ClientResponse.java#L524): Change this condition so that it does not always evaluate to "true" [rule](https://sonarqube.nla.gov.au/coding_rules#rule_key=squid%3AS2583)

**Comment by nlabuilder** [comment]
Build finished.

**Comment by shuangzhou** [comment]
@sjacob also junit latest version is 4.12 and jdbi 2.73.

**Comment by shuangzhou** [comment]
👍

**Comment by ato** [comment]
:+1:

**Comment by ato** [comment]
Although on second reading it seems little weird to be passing the client object to every method on BlobStore. Is the idea of that to allow it to be overidden temporarily for one operation?

**Comment by ato** [comment]
Oh I guess the issue is that the remote blobstore needs to forward the information about who made the request to the local blobstore in the server. Yeah.. that's awkward.

**Pull request merged**
