### PR TITLE
DPM-52: Updated DOSS to support collections and associated access permissions

### PR DESCRIPTION
**Pull request by sjacob**
@ninhnguyen @ato @brycollins @jrixon @yetti @scoen  @terenceingram 
This change updates DOSS to add support for collections and some associated access permissions. I have attempted to the number of a API interface changes to a minimum.

Each blob will now be attached to a collection. When the BlobStore is initially created, there is only one collection called "Default" and all existing blobs in the store will be attached to it. All clients of the LocalBlobStore are automatically are given write access to this collection the first time they connect to the BlobStore.

New collections can be created using the command line:

collection -i <id> -n <name>

Both the id and name must be unique. I have assumed that that there would be relatively few collections defined in a BlobStore. And that collection names can't be modified once created.

Clients can be given access to new collections using the access command:

access -a <none,read,write> -c <collection name> -u <client> -h <host>

Changes to the access permissions won't become active until the client reconnects to the BlobStore as they are cached in the Client object.

If a client has read access for a collection then they can read all blobs within it. Similarly, if a client has write access then they can begin() and resume() blob transactions for that collection. I have assumed that a client will only write to one collection for the life of a connection to the BlobStore. There is a method Client.setActiveCollection(collectionId) to change to a new collection but it isn't thread safe. I'm not sure if I should remove it or not.

For the LocalBlobStore, the connected client is still defined by the jvm parameter "-Dnla.node". But instead of using the JMX name for the host part, it just uses the java local host name. I'm not sure how reliable that will be. Also the TXS table still records the client as name@host instead of the using the client identifier. As it is basically an audit table, I will probably leave it like that.

### CODE REVIEW

**Comment by ninhnguyen** [comment]
👍

**Comment by nlabuilder** [comment]
SonarQube analysis reported 4 issues

1. MAJOR [Main.java#L3](https://github.com/nla/doss/blob/835529394f42551559af208c85c18779f94e0dc4/src/doss/Main.java#L3): Add a private constructor to hide the implicit public one. [rule](https://sonarqube.nla.gov.au/coding_rules#rule_key=squid%3AS1118)
1. MINOR [LocalBlobStore.java#L3](https://github.com/nla/doss/blob/835529394f42551559af208c85c18779f94e0dc4/src/doss/local/LocalBlobStore.java#L3): Remove this unused import 'java.io.File'. [rule](https://sonarqube.nla.gov.au/coding_rules#rule_key=squid%3AUselessImportCheck)
1. MINOR [LocalBlobStore.java#L9](https://github.com/nla/doss/blob/835529394f42551559af208c85c18779f94e0dc4/src/doss/local/LocalBlobStore.java#L9): Remove this unused import 'doss.Blob'. [rule](https://sonarqube.nla.gov.au/coding_rules#rule_key=squid%3AUselessImportCheck)
1. MINOR [LocalBlobStore.java#L16](https://github.com/nla/doss/blob/835529394f42551559af208c85c18779f94e0dc4/src/doss/local/LocalBlobStore.java#L16): Declare "dataDir" on a separate line. [rule](https://sonarqube.nla.gov.au/coding_rules#rule_key=squid%3AS1659)

**Comment by nlabuilder** [comment]
SonarQube analysis reported 2 issues

1. MAJOR [Main.java#L26](https://github.com/nla/doss/blob/835529394f42551559af208c85c18779f94e0dc4/src/doss/Main.java#L26): Add the "@Override" annotation above this method signature [rule](https://sonarqube.nla.gov.au/coding_rules#rule_key=squid%3AS1161)
1. MAJOR [Main.java#L71](https://github.com/nla/doss/blob/835529394f42551559af208c85c18779f94e0dc4/src/doss/Main.java#L71): Either log or rethrow this exception. [rule](https://sonarqube.nla.gov.au/coding_rules#rule_key=squid%3AS1166)

**Comment by nlabuilder** [comment]
Can one of the admins verify this patch?

**Comment by nlabuilder** [comment]
SonarQube analysis reported 4 issues

1. MAJOR [Main.java#L34](https://github.com/nla/doss/blob/835529394f42551559af208c85c18779f94e0dc4/src/doss/Main.java#L34): Add the "@Override" annotation above this method signature [rule](https://sonarqube.nla.gov.au/coding_rules#rule_key=squid%3AS1161)
1. MAJOR [Main.java#L70](https://github.com/nla/doss/blob/835529394f42551559af208c85c18779f94e0dc4/src/doss/Main.java#L70): Add the "@Override" annotation above this method signature [rule](https://sonarqube.nla.gov.au/coding_rules#rule_key=squid%3AS1161)
1. MAJOR [Main.java#L121](https://github.com/nla/doss/blob/835529394f42551559af208c85c18779f94e0dc4/src/doss/Main.java#L121): Either log or rethrow this exception. [rule](https://sonarqube.nla.gov.au/coding_rules#rule_key=squid%3AS1166)
1. MAJOR [Main.java#L145](https://github.com/nla/doss/blob/835529394f42551559af208c85c18779f94e0dc4/src/doss/Main.java#L145): Add the "@Override" annotation above this method signature [rule](https://sonarqube.nla.gov.au/coding_rules#rule_key=squid%3AS1161)

**Comment by ato** [comment]
Looks very solid to me. Nice work.  :+1:

Bry and I dicussed this PR. Both happy to merge. A couple of observations (which you've probably already thought about) came out of the discussion but don't affect this PR itself.

* For RemoteBlobStore a stronger credential (derived from the public key or a token or whatever if some other protocol is used) would need to be used rather than app name + hostname which could be trivially spoofed. Obviously LocalBlobStore provides no meaningful security though anyway so this PR is fine.
* Similarly for RemoteBlobStore it would good to have a no access default for production. But I think the writable default collection is right call for LocalBlobStore and it provides an upgrade path that doesn't break anything.

**Pull request merged**
